### ISSUE TITLE
Add CLI arguments for autostart

### ISSUE THREAD

**Issue by hzpc-joostk** [handruin/spdif-ka#2]
Hi @handruin, 

thank you for this tiny, though great, application! I may have a nice idea to improve it. 
Since I want to start the app during system boot, I create a task in Windows Task Scheduler. 

Unfortunately it then shows the main window, from there I have to start and minimize it manually. 
Maybe these steps could be skipped using a command line argument like:
* `-s`, `--start`
* `-h`, `--hide` or `-b`, `--background` or `-t`, `--tray`

(Where the hyphens may be substituted by a slash `/`.)

Let me know what you think. I have no experience with C#, so I cannot make a coding suggestion and create a pull request...

**Comment by handruin** [comment]
Hi @hzpc-joostk ,

No problem, I'm glad it's useful for you!  You're absolutely right in suggesting the new feature.  I use this tool on my home system and it bugs me that I haven't made a feature to have it run minimized right in the task tray on startup.  I actually start it from the windows startup menu item so I'm curious how you integrated it into the windows task scheduler.  Perhaps the best way for me to do this is to implement the feature as you proposed and also create a build with an installer that offers the option to startup on boot.  This way it can be started and minimized together.

This app also pops up the help bubble every time it's minimized which isn't needed after the first time it's installed so I can work to change that also. 

I'll add your suggestions into the bug/feature list and I'll see if I can get to them soon.  Thanks for the feedback.

**Comment by hzpc-joostk** [comment]
Hi @handruin,

It seems I have just blew the dust off this project. :smiley: 
The Task Scheduler thing is quite easy. Manually:
Start `taskschd.msc` and create a new basic task in the library:
1. Name it `SPDIF-KA`
2. Trigger on log on
3. Action is to start a program
4. Point to the program

And you may test your new task by right clicking on it and then run! (Or take the time to logon again.)

You could provide a utility to install the task, which might be as easy as a .bat file. Have a look at this: https://technet.microsoft.com/en-us/library/cc772785(v=ws.10).aspx#BKMK_logon

Good idea about the helpful balloon. #3

**Comment by handruin** [comment]
Just to give you an update on this feature, I am working on it but in a slightly different and simplified way from previously described.  instead of adding in the complexity of CLI commands, I'm going to have the utility remember its state.  I realize this isn't perfect but I will expand on it once it is implemented more.  For the first phase it should remember that the utility was running and minimized (or if it was stopped and minimized, etc) so that the next time spdifka is started it will use the same state it was left in prior to this.

Once that is working I will add GUI-based options to allow you to configure the state as-desired.  It will only be the very first time ever installing or running this tool that you will have to configure it.

None the less, I've created a new feature branch to try and add this new functionality in as it is causing a slight bit of changes under the covers which are disruptive.  I had to partially-commit my changes for now as I need to step away for a bit but once I'm available again I'll add in the feature and merge it into the master branch.

**Comment by hzpc-joostk** [comment]
@handruin Right, that seems OK to me too. As the only functionality of this app is to start or stop a silent sound, it may seem logical to automatically utilize its purpose when the app starts. :+1:

**Comment by handruin** [comment]
@hzpc-joostk The new code changes are checked in and merged to master.  I've created a new build and it is posted in the release section of this project as version 1.1.0.  Let me know if you have any issues and I'll work to get them fixed!  Thanks for using this tool and giving me feedback.

**Comment by hzpc-joostk** [comment]
Great! The apps works flawlessly (on Windows 10 Pro x64).
